//! External editor integration for the DynamoDB items view.
//!
//! # What this does
//!
//! 1. Validates the editor binary against `ALLOWED_EDITORS`.
//! 2. Writes `initial_json` to a temp file.
//! 3. Suspends the Ratatui / crossterm raw-mode terminal.
//! 4. Spawns the editor in-process (blocking the tokio task, NOT the TUI thread).
//! 5. Drains stray terminal capability responses from stdin (50 ms deadline).
//! 6. Re-enters raw mode and re-initialises the alternate screen.
//! 7. Reads the file back, validates JSON, and sends
//!    `Action::DynamoDB(DdbAction::EditorDone {...})` on the channel.
//!
//! # Security
//!
//! - The editor binary is validated against `config::ALLOWED_EDITORS`.
//! - `std::process::Command` is used directly — **no shell** is involved, so
//!   there is no injection surface (`exec(2)` semantics).
//! - The temp file path is generated by `tempfile::NamedTempFile`; it is never
//!   derived from user input.

use std::{
    io::Read,
    time::{Duration, Instant},
};

use tokio::sync::mpsc::UnboundedSender;

use crate::{
    action::Action,
    config::ALLOWED_EDITORS,
    services::dynamodb::DdbAction,
};

/// Minimum valid JSON for a new item.
pub const EMPTY_ITEM_JSON: &[u8] = b"{\n  \n}\n";

/// Spawn a tokio task that opens the configured editor on `initial_json` and
/// sends `Action::DynamoDB(DdbAction::EditorDone {...})` when done.
///
/// `editor` is the binary name from config (e.g. `"nvim"`).
pub fn spawn_editor(editor: String, initial_json: Vec<u8>, tx: UnboundedSender<Action>) {
    tokio::spawn(async move {
        // Validate editor on a blocking thread so we don't block the runtime.
        let result = tokio::task::spawn_blocking(move || {
            run_editor_sync(&editor, &initial_json)
        })
        .await;

        let outcome = match result {
            Ok(outcome) => outcome,
            Err(join_err) => Err(format!("editor task panicked: {join_err}")),
        };

        match outcome {
            Ok(data) => {
                let _ = tx.send(Action::DynamoDB(DdbAction::EditorDone {
                    data: Some(data),
                    error: None,
                }));
            }
            Err(e) => {
                let _ = tx.send(Action::DynamoDB(DdbAction::EditorDone {
                    data: None,
                    error: Some(e),
                }));
            }
        }
    });
}

// ── Synchronous editor execution (runs in spawn_blocking) ─────────────────────

fn run_editor_sync(editor: &str, initial_json: &[u8]) -> Result<Vec<u8>, String> {
    // 1. Validate editor binary.
    if !ALLOWED_EDITORS.contains(&&editor[..]) {
        return Err(format!(
            "editor {:?} is not permitted — allowed: {}",
            editor,
            ALLOWED_EDITORS.join(", ")
        ));
    }

    // 2. Write to a named temp file.
    let tmp = tempfile::Builder::new()
        .prefix("cumulus-")
        .suffix(".json")
        .tempfile()
        .map_err(|e| format!("creating temp file: {e}"))?;

    std::fs::write(tmp.path(), initial_json)
        .map_err(|e| format!("writing temp file: {e}"))?;

    let tmp_path = tmp.path().to_path_buf();

    // 3. Suspend Ratatui / crossterm.
    let _ = crossterm::terminal::disable_raw_mode();
    let _ = crossterm::execute!(
        std::io::stdout(),
        crossterm::terminal::LeaveAlternateScreen,
        crossterm::event::DisableMouseCapture,
    );

    // 4. Run editor (blocking; not through a shell). // #nosec G204
    let status = std::process::Command::new(editor)
        .arg(&tmp_path)
        .status()
        .map_err(|e| {
            // Re-enter terminal before returning error so the TUI can recover.
            let _ = reenter_terminal();
            format!("launching editor {editor:?}: {e}")
        })?;

    // 5. Drain stray terminal capability responses (50 ms).
    drain_stdin(Duration::from_millis(50));

    // 6. Re-enter raw mode.
    reenter_terminal().map_err(|e| format!("restoring terminal: {e}"))?;

    if !status.success() {
        return Err(format!(
            "editor exited with status {}",
            status.code().unwrap_or(-1)
        ));
    }

    // 7. Read file back and validate JSON.
    let data = std::fs::read(&tmp_path) // #nosec G304 — our own temp file
        .map_err(|e| format!("reading temp file: {e}"))?;

    let _: serde_json::Value = serde_json::from_slice(&data)
        .map_err(|e| format!("result is not valid JSON: {e}"))?;

    Ok(data)
}

fn reenter_terminal() -> Result<(), String> {
    crossterm::terminal::enable_raw_mode()
        .map_err(|e| format!("enable_raw_mode: {e}"))?;
    crossterm::execute!(
        std::io::stdout(),
        crossterm::terminal::EnterAlternateScreen,
        crossterm::event::EnableMouseCapture,
    )
    .map_err(|e| format!("entering alternate screen: {e}"))?;
    Ok(())
}

/// Drain stray bytes from stdin for at most `deadline` (vim/nvim emit terminal
/// capability queries like DA2 / t_RV that arrive on stdin after the editor
/// exits; without draining they leak into the TUI input loop).
fn drain_stdin(deadline: Duration) {
    use std::io::Read;

    // We need a non-blocking read with a timeout. On Unix we can use
    // `set_nonblocking` on stdin and poll with a sleep loop.
    #[cfg(unix)]
    {
        use std::os::unix::io::AsRawFd;
        let stdin = std::io::stdin();
        let fd = stdin.as_raw_fd();
        // Set non-blocking.
        unsafe {
            let flags = libc_fcntl_get(fd);
            libc_fcntl_set(fd, flags | libc_o_nonblock());
        }

        let start = Instant::now();
        let mut buf = [0u8; 256];
        let mut handle = stdin.lock();
        loop {
            if start.elapsed() >= deadline {
                break;
            }
            match handle.read(&mut buf) {
                Ok(0) | Err(_) => {
                    std::thread::sleep(Duration::from_millis(5));
                    if start.elapsed() >= deadline {
                        break;
                    }
                }
                Ok(_) => {} // consumed some bytes, keep draining
            }
        }

        // Restore blocking.
        unsafe {
            let flags = libc_fcntl_get(fd);
            libc_fcntl_set(fd, flags & !libc_o_nonblock());
        }
    }

    // On non-Unix platforms, just sleep for the deadline duration.
    #[cfg(not(unix))]
    {
        std::thread::sleep(deadline);
    }
}

// ── Minimal libc shims (avoid a hard libc dep) ────────────────────────────────

#[cfg(unix)]
fn libc_o_nonblock() -> i32 {
    // O_NONBLOCK is 0x800 on Linux/x86-64 and 0x0004 on macOS; use the
    // platform constant via nix or just the known value.
    // On macOS O_NONBLOCK = 4; on Linux O_NONBLOCK = 2048.
    #[cfg(target_os = "macos")]
    return 0x0004;
    #[cfg(not(target_os = "macos"))]
    return 0x0800;
}

#[cfg(unix)]
fn libc_fcntl_get(fd: i32) -> i32 {
    unsafe { libc_fcntl(fd, 3 /*F_GETFL*/, 0) }
}

#[cfg(unix)]
fn libc_fcntl_set(fd: i32, flags: i32) {
    unsafe {
        libc_fcntl(fd, 4 /*F_SETFL*/, flags);
    }
}

#[cfg(unix)]
unsafe fn libc_fcntl(fd: i32, cmd: i32, arg: i32) -> i32 {
    extern "C" {
        fn fcntl(fd: i32, cmd: i32, ...) -> i32;
    }
    fcntl(fd, cmd, arg)
}
